### ISSUE TITLE
Why do I get an error?

### ISSUE THREAD

**Issue by stephenplusplus** [stephenplusplus/grpc-usage-question#1]
@murgatroid99

I was trying to set access Logging IAM settings through gRPC, and came upon some errors. This is a test case that I can't seem to get past, and I'm assuming it's something obvious I'm missing. Can you take a quick look at this repo and let me know where I might be going wrong?

**Comment by murgatroid99** [comment]
The error code you're getting is CANCELLED. I am pretty sure there is nothing in the Node client that explicitly outputs that code. The object you're getting is an error object; does the message have any useful information? Are you getting any other logging?

**Comment by stephenplusplus** [comment]
Thanks for checking this out. I traded my `console.log(err)` with `console.log(err.stack)` and got:

I get either of these errors: 

```
E0412 11:43:47.803555000 123145307668480 frame_data.c:168] Bad GRPC frame type 0x3c
{ [Error: Received RST_STREAM err=1] code: 13, metadata: Metadata { _internal_repr: {} } }
Error: Received RST_STREAM err=1
    at /Users/stephen/dev/grpc-usage-question/node_modules/grpc/src/node/src/client.js:411:17
```

```
{ [Error] code: 1, metadata: Metadata { _internal_repr: {} } }
Error
    at /Users/stephen/dev/grpc-usage-question/node_modules/grpc/src/node/src/client.js:411:17
```

**Comment by stephenplusplus** [comment]
Updated the post above with some more info.

**Comment by murgatroid99** [comment]
It looks to me like the server is responding with a CANCELLED status and no additional information. The first log you are getting may be a gRPC core bug related to how it handles a non-OK status.

**Comment by stephenplusplus** [comment]
Okay, thanks again for looking.

@jgeewax -- is there anyone working on IAM who can help out?

**Comment by jgeewax** [comment]
Are you auth'ing as yourself here? or a service account? google-auto-auth does multiple, right ?

**Comment by stephenplusplus** [comment]
This is as myself if I run `gcloud auth login`.
